### ISSUE TITLE
Woow is it really true?

### ISSUE THREAD

**Issue by alighasemzadeh** [PH7-Jack/quasar-tailwind#1]
Woow is it really true?
Can we use tailwind and alpine like quasar?

**Comment by PH7-Jack** [comment]
Its true
Can use [Quasar Framework](https://quasar.dev/) with [Tailwindcss](https://tailwindcss.com/)

This project has a quasar + tailwindcss configured

**Comment by PH7-Jack** [comment]
If you refer [alpine](https://github.com/alpinejs/alpine), it not is configured

**Comment by alighasemzadeh** [comment]
Then is postCSS plugin.

**Comment by alighasemzadeh** [comment]
@PH7-Jack 
Do you have any example using quasar and laravel api to build spa application?

**Comment by PH7-Jack** [comment]
I don't have one, but vuejs shows how to make requests via api using axios

https://br.vuejs.org/v2/cookbook/using-axios-to-consume-apis.html
